const express = require('express');
const connectDB = require('./config/db');
const dotenv = require('dotenv');
dotenv.config();
const app = express();
connectDB();
app.use(express.json());
app.use('/users', require('./routes/users'));
app.use('/:user_id/timer', require('./routes/timers'));
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Server started on port ${PORT}`));
